[tool.poetry]
name = "myfirst-ml-dl"
version = "0.1.0"
description = ""
authors = ["mingdul <jmjang2122@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
